### PR TITLE
Update ODT

### PR DESCRIPTION
**Pull request by boscorelly**
Update to version 16.0.15928.20216

### CODE REVIEW

**Review by jordigg — APPROVED** [review]
Hi @boscorelly, thanks for sending this update over.

The new version is current and the SHA matches. Approving.
Will generate the package file and submit to Choco now. I'm looking if this package can be added to the automated and maintained repos from choco so it runs on its own.

Thanks so much one again!

**Comment by boscorelly** [comment]
you're requested to validate the update

https://community.chocolatey.org/packages/Office365Business/15928.20216

**Comment by jordigg** [comment]
Checking. The automated testing failed due to a timeout but works locally. I'm trying to re-run or re-submit.

Thanks for letting me know, somehow I missed the notification.

**Comment by boscorelly** [comment]
still not updated :(

**Comment by jordigg** [comment]
Choco team keep asking me to wait, nothing I can really do. I saw there is another choco package that provides the Office Deployment tool, almost a clone, and is also pending review as it times-out during testing.

The only way for now is to force install the latest version. If you don't specify the version it will use the latest "verified" version available but you can force this latest update that is still pending review. I'll keep asking.

**Pull request merged**
